services:
  postgres:
    image: postgres:17
    container_name: todo_list_ai_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_list_ai_db
    ports:
      - "5432:5432"
    volumes:
      - todo_list_ai_db_pgdata:/var/lib/postgresql/data

volumes:
  todo_list_ai_db_pgdata:
